name: Deploy Demo App
run-name: Deploy Demo App To Staging After Merge

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: ğŸ’¾ Checking out the repository
        uses: actions/checkout@v4
      - name: âš™ï¸ Setting up the MonkJs project
        uses: ./.github/actions/monkjs-set-up
      - name: ğŸ“± Building the demo app
        run: yarn build:demo-app:staging
      - name: ğŸ“¦ Uploading the artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build-demo-app-staging
          path: apps/demo-app/build

  deploy:
    name: Deploy
    environment: staging
    needs:
      - build
    container:
      image: dtzar/helm-kubectl:3.14.2
    runs-on: ubuntu-latest
    env:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
    steps:
      - name: Log stuff into the console
        run: |-
          echo GKE_CLUSTER = ["$GKE_CLUSTER"]
          echo GKE_CLUSTER = ["$GKE_CLUSTER"]
          echo GKE_ZONE = ["$GKE_ZONE"]
          echo GKE_PROJECT = ["$GKE_PROJECT"]
      - name: ğŸ” Authenticating to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"
      - name: ğŸ” Obtaining GKE credentials
        uses: google-github-actions/get-gke-credentials@v2.1.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: ğŸ“¦ Downloading the artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: build-demo-app-staging
          path: demo
      - name: ğŸ§¹ Cleaning up previous build
        run: |-
          kubectl -n poc exec -it $(kubectl get pods -n poc -l app.kubernetes.io/instance=poc-spa --no-headers | awk '{print $1}') -- rm -rf demo
      - name: ğŸŒ Deploying app
        run: |-
          kubectl -n poc cp demo poc/$(kubectl get pods -n poc -l app.kubernetes.io/instance=poc-spa --no-headers | awk '{print $1}'):/app/
